### ISSUE TITLE
[Question] Server side implementation ?

### ISSUE THREAD

**Issue by hajime-moto** [Stratio/Spray-Oauth2#1]
Hi, 

Thank you for this great oauth client library. I'm also in need of a spray oauth provider (server side). Any plans of implementing the server side ? or is there an existing implementation that you would recommend ?

**Comment by arinconstrio** [comment]
Hi, 

We haven't got any plan (medium-term) to implement the server, as Oauth server we're using  [CAS](https://wiki.jasig.org/display/CASUM/Configuration+for+the+OAuth+server+support)

Regards,
